ensure-ansible-lint: install community roles
- bullseye ansible-lint has been pinned for clarity. The version remain
  the same
- bookworm ansible-lint has been set to 6.22.2 despite the fact that
  pip will raise the following error because the "minimal correct"
  version is 6.16.2 but contains an issue with 'var-naming[no-role-prefix]'.
  So we set the same version than bullseye to be "safe"

  ```
  ERROR: pip's dependency resolver does not currently take into account
  all the packages that are installed. This behaviour is the source of the
  following dependency conflicts.
  ansible 7.7.0 requires ansible-core~=2.14.7, but you have ansible-core
  2.19.2 which is incompatible.
  ```